[workspace]
changelog_update = true
features_always_increment_minor = false
git_release_draft = false
git_release_enable = true
git_release_latest = true
git_release_name = "v{{ version }}"
git_release_type = "prod"
git_tag_enable = true
git_tag_name = "v{{ version }}"
semver_check = true

[[package]]
name = "authzen-rs"
publish = true

[changelog]
protect_breaking_commits = true
tag_pattern = "v[0-9].*"
